project:
  name: quickstart-microsoft-wapadfs
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-1
  - ap-southeast-1
#  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
#  - eu-west-2
#  - us-east-1
#  - us-west-1
  - us-west-2
tests:
  wapadfs:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      DomainAdminPassword: $[taskcat_genpass_8S]
      KeyPairName: $[taskcat_getkeypair]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      NumberOfRDGWHosts: '0'
      RDGWCIDR: 10.0.0.0/16
    template: ./templates/wap-adfs-master.template
