project:
  name: quickstart-microsoft-wapadfs
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
  - ap-northeast-1
  - ap-southeast-1
  - ap-southeast-2
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - us-east-1
  - us-west-1
  - us-west-2
tests:
  wapadfs:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      ADServer1NetBIOSName: DC-wapadfs-1
      ADServer2NetBIOSName: DC-wapadfs-2
      ADServer1PrivateIP: "10.0.0.10"
      ADServer2PrivateIP: "10.0.32.10"
      DomainAdminPassword: $[taskcat_genpass_8S]
      DomainAdminUser: StackAdmin
      DomainDNSName: example.com
      KeyPairName: $[taskcat_getkeypair]
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      RDGWCIDR: 10.0.0.0/16
    template: ./templates/wap-adfs-master.template
